name: Deploy to Oracle Cloud Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Oracle Cloud Infrastructure
        uses: oracle-actions/oraclecloud-deploy@v1
        with:
          cloud-id: ocid1.cloud.oracle.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          tenancy-id: ocid1.tenancy.oc1..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          user-id: ocid1.user.oc1..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx