services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
    networks:
      - portfolio-net

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge
