services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - portfolio-network
    # Criar um volume para desenvolvimento - descomente se quiser desenvolvimento ao vivo
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    # Adicionar configuração para o frontend acessar o backend via proxy
    environment:
      # Esta variável permite que o React saiba que está rodando no Docker
      - VITE_API_URL=http://localhost:4000

  # Configurar o Nginx para fazer proxy das requisições /api para o backend
  # Vamos adicionar um nginx.conf personalizado no frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      # Configurar CORS para permitir requisições do frontend
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - portfolio-network
    # Criar um volume para desenvolvimento - descomente se quiser desenvolvimento ao vivo
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules

networks:
  portfolio-network:
    driver: bridge
