version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    # Descomente para desenvolvimento
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # ports:
    #   - "3000:3000"
    # command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge