name: Deploy to Oracle Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Deploy to Oracle Cloud VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME_SSH }}@${{ secrets.HOST_SSH }} << 'EOF'
          cd /home/app
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          gh auth login --with-token <<< $GH_TOKEN
          if [ ! -d ".git" ]; then
            gh repo clone m1theusr/portfolio .
          else
            gh repo sync m1theusr/portfolio
          fi
          docker compose down
          docker compose up -d
        EOF