name: Deploy to Oracle Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install SSH client and Docker Compose
      run: |
        sudo apt-get update

    - name: Deploy to Oracle Cloud VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME_SSH }}@${{ secrets.HOST_SSH }} << 'EOF'
          # Navegar para o diretório onde o repositório está
          cd /home/app
          
          # Verificar se o repositório já foi clonado
          if [ ! -d ".git" ]; then
            # Clonar o repositório se ele não existir
            git clone git@github.com:${{ secrets.REPOSITORY }} .
          else
            # Atualizar o repositório com o git pull
            git pull origin main
          fi
          
          # Parar e remover containers antigos, e iniciar novos
          docker compose down
          docker compose up -d
        EOF
